name: Update hosts

on:
  schedule:
    - cron: '0 0 1,15 * *'

  workflow_dispatch:

jobs:
  update-hosts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: |
          npm ci
          npm run update-hosts
          git diff --quiet || {
            msg='Update hosts'
            git config --global user.email "feeling@lost.st"
            git config --global user.name "Robocop"
            tag="$(npm version patch -m "${msg}" --no-git-tag-version)"
            tag="${tag#v}"
            git add .
            git commit -m "PATCH: ${msg}"
            git tag "${tag}"
            git push origin main
            git push origin --tags
            gh release create "${tag}" --notes "${msg}"
          }
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
